version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of your build.gradle file
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "direct"
