name: Trigger Cleanup Script

on:
  workflow_dispatch:

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Allow push access

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 🧼 Make cleanup script executable
        run: chmod +x clean_fixed.sh

      - name: 🧹 Run cleanup
        run: bash clean_fixed.sh
