name: Semgrep Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan and save SARIF
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
        env:
          SEMGREP_RULES: auto
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
