name: semgrep

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan and save SARIF
        uses: returntocorp/semgrep-action@v1
        with:
          args: --sarif --output semgrep.sarif

      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
