name: semgrep

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and generate SARIF
        run: semgrep scan --config auto --sarif --output semgrep.sarif

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
