name: Trigger Fix Script

on:
  workflow_dispatch:

jobs:
  run-fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Allow pushing code to the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use GitHub Actions token

      - name: Run fix.sh
        run: bash fix.sh
