name: Run CVE Fix Script

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run fix.sh
        run: bash fix.sh
