name: Trivy Dockerfile Scan

on:
  push:
    paths:
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    name: Scan Dockerfile with Trivy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './Dockerfile'
          format: 'table'
          output: 'trivy-report.txt'

      - name: Upload Trivy Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dockerfile-report
          path: trivy-report.txt
