name: Trivy Docker Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Scan Dockerfile with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Build Docker Image
        run: docker build -t insecure-token-app .

      - name: Run Trivy Scan on Image
        run: |
          trivy image --format table --severity CRITICAL,HIGH --output trivy-report.txt insecure-token-app

      - name: Upload Trivy Report as Artifact
        uses: actions/upload-artifact@v4  # ✅ updated from @v3 to @v4
        with:
          name: trivy-report
          path: trivy-report.txt
